#!/usr/bin/env python3
import os

# CONFIGURATION
# Sources
CSS_BASE = "PRODUCTION/ui/common/base.css"
CSS_DESKTOP = "PRODUCTION/ui/desktop/desktop_styles.css"
CSS_MOBILE = "PRODUCTION/ui/mobile/mobile_styles.css"

HTML_HEADER_DESKTOP = "PRODUCTION/templates/desktop/header_desktop.html"
HTML_HEADER_MOBILE = "PRODUCTION/templates/mobile/header_mobile.html"

# Outputs
OUTPUT_CSS = "PRODUCTION/ui/master_styles.css"
OUTPUT_HEADER = "PRODUCTION/templates/header.html"

def read_file(path):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: File not found: {path}")
        return ""

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Built: {path}")

def build_css():
    print("Building CSS...")
    base = read_file(CSS_BASE)
    desktop = read_file(CSS_DESKTOP)
    mobile = read_file(CSS_MOBILE)

    # Wrap Device Specifics in Media Queries
    # Note: We wrap strictly to ensure no leakages if the file didn't have them
    
    desktop_wrapped = f"""
/* === DESKTOP STYLES (Built from {CSS_DESKTOP}) === */
@media screen and (min-width: 641px) {{
    /* Hide Mobile Root if present */
    .nova-mobile-root {{ display: none !important; }}
    
{desktop}
}}
"""

    mobile_wrapped = f"""
/* === MOBILE STYLES (Built from {CSS_MOBILE}) === */
@media screen and (max-width: 640px) {{
    /* Hide Desktop Root if present */
    .nova-desktop-root {{ display: none !important; }}

{mobile}
}}
"""

    final_css = f"""/* === MASTER STYLES (AUTO-GENERATED) === */
/* Do not edit this file directly. Edit the files in ui/common, ui/desktop, ui/mobile and run build.py */

{base}

{desktop_wrapped}

{mobile_wrapped}
"""
    write_file(OUTPUT_CSS, final_css)

def build_header():
    print("Building Header...")
    desktop_html = read_file(HTML_HEADER_DESKTOP)
    mobile_html = read_file(HTML_HEADER_MOBILE)

    final_html = f"""<!-- === MASTER HEADER (AUTO-GENERATED) === -->
<!-- Contains both Desktop and Mobile versions. CSS controls visibility. -->

<!-- DESKTOP PART -->
{desktop_html}

<!-- MOBILE PART -->
{mobile_html}
"""
    write_file(OUTPUT_HEADER, final_html)

def main():
    root_dir = "/Users/andreyfilatiev/Projects/Ёжкин ролл/Сайт" 
    # Change WD if script is run from elsewhere, but assuming we run relative to project root
    # or finding the files relative to CWD. Use absolute paths if needed or rely on user CWD.
    if os.path.exists(root_dir):
        os.chdir(root_dir)
        
    build_css()
    build_header()
    print("Build Complete.")

if __name__ == "__main__":
    main()
